import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import Image from "next/image";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "My Personal Website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className="max-w-3xl mx-auto py-5 flex flex-col min-h-screen">
        <header className="flex items-center justify-between">
          <Link href="/">
            <div className="relative">
              <p className="absolute bottom-4 font-serif text-[10px] h-fit w-full bg-[#D6DCDB] dark:bg-black text-center dark:text-gray-200 light:text-gray-600">
                Adam Dowsett
              </p>
              <p className="font-serif text-5xl text-blue-500 text-center">
                AD
              </p>
            </div>
            {/* <Image src="/logoAdam.png" alt="logo" width={70} height={70} /> */}
          </Link>
          <div className="flex items-center gap-5 text-sm dark:text-gray-200 light:text-gray-600">
            <Link href="/about" className="hover:underline">
              About
            </Link>
          </div>
        </header>
        <main className="py-5">{children}</main>
        <footer className="flex items-center justify-around gap-5 text-sm dark:text-gray-300 light:text-gray-600 mt-auto">
          <a
            href="https://www.linkedin.com/in/adam-dowsett-94514b241/"
            className="transition duration-300 transform hover:scale-110"
          >
            <Image
              src="/linkedinblue.png"
              alt="linkedin"
              width={50}
              height={50}
            />
          </a>
          <a
            href="https://github.com/Adam-Dowsett"
            className="transition duration-300 transform hover:scale-110"
          >
            <Image src="/github.png" alt="github" width={50} height={50} />
          </a>
        </footer>
      </body>
    </html>
  );
}
